#!/usr/bin/env bash
set -e

IMAGE_SNAPSHOT_REPOSITORY="$CONTAINER_REPO_PATH_PREFIX/sandpit"
IMAGE_BASE_NAME="telegram-bot"
IMAGE_REPO="$IMAGE_SNAPSHOT_REPOSITORY/snapshots/$IMAGE_BASE_NAME"
IMAGE_PRODUCT_TAG="1.0.0"

docker build -t  "$IMAGE_REPO:$IMAGE_PRODUCT_TAG" .
docker push "$IMAGE_REPO:$IMAGE_PRODUCT_TAG"